### ISSUE TITLE
Dark theme ?

### ISSUE THREAD

**Issue by florentulve** [Rapptz/power-tabs#3]

**Comment by Rapptz** [comment]
I'm in the process of tackling this for the next version but it's actually a little more annoying than anticipated. 

Due to the arbitrary colour situation that one can assign to groups, I require a redesign in how those colours are applied to make it at least somewhat passable in both light and dark theme (of course, it is up to the user to pick a colour that looks good in whatever theme they use). I also need to change the fill colour of every icon that is used in the same manner to fit with the Photon guidelines.

On the bright side a more consistent design on those arbitrary colour groups should be quite handy.

**Comment by Rapptz** [comment]
This should be live in AMO now.
